/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertTemplate: typeof import('./src/components/alertTemplate/alertTemplate.vue')['default']
    CodeTemplate: typeof import('./src/components/codeTemplate/codeTemplate.vue')['default']
    CommonTemplate: typeof import('./src/components/commonTemplate/commonTemplate.vue')['default']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IconEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    IconEpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
